# Generated by Django 4.2 on 2023-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("isbn", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("inventory", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Book_Purchase",
            fields=[
                (
                    "purchase_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("number_of_purchase", models.IntegerField()),
                ("purchase_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book_Stock",
            fields=[
                (
                    "stock_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("number_of_stock", models.IntegerField()),
                ("stock_date", models.DateField(auto_now=True)),
                ("is_paid", models.BooleanField()),
                ("is_returned", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Stock_Payment",
            fields=[
                (
                    "payment_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("payment_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock_Return",
            fields=[
                (
                    "return_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("return_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("personal_id", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50, null=True)),
                ("age", models.IntegerField()),
                ("is_superuser", models.BooleanField()),
            ],
        ),
    ]
