# Generated by Django 4.2 on 2023-04-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Book_DBMS", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Bill",),
        migrations.AddField(
            model_name="book_purchase",
            name="ref_book_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Book_DBMS.book_stock",
            ),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="book",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Book_DBMS.book",
            ),
        ),
        migrations.AddField(
            model_name="stock_payment",
            name="ref_stock_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Book_DBMS.book_stock",
            ),
        ),
        migrations.AddField(
            model_name="stock_return",
            name="ref_stock_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Book_DBMS.book_stock",
            ),
        ),
        migrations.AlterField(
            model_name="book_purchase", name="purchase_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="stock_payment", name="payment_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="stock_return", name="return_date", field=models.DateField(),
        ),
    ]
