# Generated by Django 4.2 on 2023-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book_DBMS", "0002_delete_bill_book_purchase_ref_book_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="book_stock", name="book",),
        migrations.AddField(
            model_name="book_stock",
            name="author",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="book_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="isbn",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="publisher",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="book_stock",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
