# Generated by Django 4.2 on 2023-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookDBMS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
